{% set name = "pybcpy" %}
{% set version = "0.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bbf0360fffa6fd1c13a1f783373b22a85e70c97f323c4342fe89cce615a813d
  patches: 
    - setup.patch

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pybcpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kr-g/pybcpy
  summary: pybcpy - backup copy - utility
  license: LicenseRef-pybcpy
  license_family: AGPL
  license_file: LICENSE
  doc_url: https://pypi.org/project/pybcpy/

extra:
  recipe-maintainers:
    - sarthakpati
